Check for and link against libplist
src/linux/up-device-idevice.c explicitly uses libplist, so check for it in
configure.ac. With gcc 4.5 private requirements of libraries aren't
transitively linked any more, thus the build fails with

  CCLD   upowerd
/usr/bin/ld.bfd.real: linux/.libs/libupshared.a(libupshared_la-up-device-idevice.o): undefined reference to symbol 'plist_dict_get_item'
/usr/bin/ld.bfd.real: note: 'plist_dict_get_item' is defined in DSO /usr/lib64/libplist.so.1 so try adding it to the linker command line
/usr/lib64/libplist.so.1: could not read symbols: Invalid operation