fix up-self-test build
It uses up_config_*() functions, so we need to build it against up-config.{h,c}

Fixes build failure:

up_self_test-up-daemon.o: In function `up_daemon_init':
/home/martin/upstream/upower/src/up-daemon.c:1047: undefined reference to `up_config_new'
[...]